### ISSUE TITLE
user story 4.1

### ISSUE THREAD

**Issue by thien113** [thien113/spiced-final-project#11]
### Value Proposition

As the Owner I want to see an Admindashboard
so I can handle the data

### Acceptance Criteria

- [ ] I see a dashboard with my logo, and my restaurant name

### Tasks

- [ ] create a admin folder inside pages
- [ ] create login page
- [ ] create dashboard page
