### ISSUE TITLE
user story 4.3 Auth

### ISSUE THREAD

**Issue by thien113** [thien113/spiced-final-project#15]
### Value Proposition

As the Owner I want to logged in into my dashboard,
so only I can access it.

### Acceptance Criteria

- [ ] logged in with credentials
- [ ] next/auth

### Tasks

- [ ] implement next/auth
- [ ] create collections for credentials, hard code credentials
- [ ] show admin page session===authenticated
